name: Build Binaries

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
            EXT: ''
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
            EXT: .exe
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
            EXT: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir -p dist
          go build -v -o dist/docker-compose-bundler-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.EXT }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-bundler-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.EXT }}
          path: dist/docker-compose-bundler-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.EXT }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          draft: false
          prerelease: false
          files: dist/**/docker-compose-bundler-*
